version: "3.8"
services:
  carsearch_api:
    container_name: carsearch_api
    build:
      context: container
      dockerfile: air.Dockerfile
      target: dev
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - carsearch
    ports:
      - 8000:8000
      - 2345:2345
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - 5432:5432
    networks:
      - carsearch
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U database"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data

volumes:
    database:

networks:
  carsearch:
    name: carsearch